/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cryptoapi

import (
	"encoding/json"
)

// AnyValue struct for AnyValue
type AnyValue struct {
}

// NewAnyValue instantiates a new AnyValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnyValue() *AnyValue {
	this := AnyValue{}
	return &this
}

// NewAnyValueWithDefaults instantiates a new AnyValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnyValueWithDefaults() *AnyValue {
	this := AnyValue{}
	return &this
}

func (o AnyValue) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	return json.Marshal(toSerialize)
}

type NullableAnyValue struct {
	value *AnyValue
	isSet bool
}

func (v NullableAnyValue) Get() *AnyValue {
	return v.value
}

func (v *NullableAnyValue) Set(val *AnyValue) {
	v.value = val
	v.isSet = true
}

func (v NullableAnyValue) IsSet() bool {
	return v.isSet
}

func (v *NullableAnyValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnyValue(val *AnyValue) *NullableAnyValue {
	return &NullableAnyValue{value: val, isSet: true}
}

func (v NullableAnyValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnyValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
