/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cryptoapi

import (
	"encoding/json"
)

// GetInstrumentsResponse struct for GetInstrumentsResponse
type GetInstrumentsResponse struct {
	Id *int32 `json:"id,omitempty"`
}

// NewGetInstrumentsResponse instantiates a new GetInstrumentsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetInstrumentsResponse() *GetInstrumentsResponse {
	this := GetInstrumentsResponse{}
	return &this
}

// NewGetInstrumentsResponseWithDefaults instantiates a new GetInstrumentsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetInstrumentsResponseWithDefaults() *GetInstrumentsResponse {
	this := GetInstrumentsResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetInstrumentsResponse) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetInstrumentsResponse) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetInstrumentsResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetInstrumentsResponse) SetId(v int32) {
	o.Id = &v
}

func (o GetInstrumentsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableGetInstrumentsResponse struct {
	value *GetInstrumentsResponse
	isSet bool
}

func (v NullableGetInstrumentsResponse) Get() *GetInstrumentsResponse {
	return v.value
}

func (v *NullableGetInstrumentsResponse) Set(val *GetInstrumentsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetInstrumentsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetInstrumentsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetInstrumentsResponse(val *GetInstrumentsResponse) *NullableGetInstrumentsResponse {
	return &NullableGetInstrumentsResponse{value: val, isSet: true}
}

func (v NullableGetInstrumentsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetInstrumentsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
